'use strict';
// ---------------------------------------------------------------------------
// Static game data: terrain, resources, units, buildings, districts, wonders,
// technologies, civics, governments, policies, beliefs and civilizations.
// ---------------------------------------------------------------------------

const ERAS = ['Ancient', 'Classical', 'Medieval', 'Renaissance', 'Industrial', 'Modern', 'Atomic', 'Information'];

const TERRAIN = {
  ocean:  { name: 'Ocean',     f: 1, p: 0, g: 0, water: true, color: '#1f4461' },
  coast:  { name: 'Coast',     f: 1, p: 0, g: 1, water: true, color: '#2f7394' },
  grass:  { name: 'Grassland', f: 2, p: 0, g: 0, color: '#5a8a3c' },
  plains: { name: 'Plains',    f: 1, p: 1, g: 0, color: '#a09a4c' },
  desert: { name: 'Desert',    f: 0, p: 0, g: 0, color: '#d6bd7e' },
  tundra: { name: 'Tundra',    f: 1, p: 0, g: 0, color: '#8b8c78' },
  snow:   { name: 'Snow',      f: 0, p: 0, g: 0, color: '#dfe6ea' },
};

const FEATURES = {
  forest: { name: 'Woods',      p: 1, move: 2, def: 3 },
  jungle: { name: 'Rainforest', f: 1, move: 2, def: 3 },
  marsh:  { name: 'Marsh',      f: 1, move: 2, def: -2 },
};

// type: bonus | luxury | strategic.  imp: improvement that works it.
const RES = {
  wheat:   { name: 'Wheat',   type: 'bonus', f: 1, imp: 'farm', on: ['grass', 'plains'], flat: true },
  cattle:  { name: 'Cattle',  type: 'bonus', f: 1, imp: 'pasture', on: ['grass'], flat: true },
  sheep:   { name: 'Sheep',   type: 'bonus', f: 1, imp: 'pasture', on: ['grass', 'plains', 'desert', 'tundra'], hills: true },
  deer:    { name: 'Deer',    type: 'bonus', p: 1, imp: 'camp', on: ['grass', 'plains', 'tundra'], feat: ['forest'] },
  stone:   { name: 'Stone',   type: 'bonus', p: 1, imp: 'quarry', on: ['grass', 'plains', 'desert'], flat: true },
  fish:    { name: 'Fish',    type: 'bonus', f: 1, water: true },
  horses:  { name: 'Horses',  type: 'strategic', f: 1, p: 1, imp: 'pasture', on: ['grass', 'plains'], flat: true, tech: 'animal' },
  iron:    { name: 'Iron',    type: 'strategic', s: 1, imp: 'mine', on: ['grass', 'plains', 'desert', 'tundra'], hills: true, tech: 'bronze' },
  niter:   { name: 'Niter',   type: 'strategic', f: 1, p: 1, imp: 'mine', on: ['plains', 'desert', 'grass'], flat: true, tech: 'milEng' },
  coal:    { name: 'Coal',    type: 'strategic', p: 2, imp: 'mine', on: ['grass', 'plains', 'tundra'], hills: true, tech: 'industrialization' },
  oil:     { name: 'Oil',     type: 'strategic', p: 3, imp: 'well', on: ['desert', 'tundra'], flat: true, tech: 'refining' },
  wine:    { name: 'Wine',    type: 'luxury', f: 1, g: 1, imp: 'plantation', on: ['grass', 'plains'] },
  silk:    { name: 'Silk',    type: 'luxury', c: 1, imp: 'plantation', on: ['grass', 'plains'], feat: ['forest'] },
  spices:  { name: 'Spices',  type: 'luxury', f: 2, imp: 'plantation', on: ['grass', 'plains'], feat: ['jungle'] },
  gems:    { name: 'Gems',    type: 'luxury', g: 3, imp: 'mine', on: ['grass', 'plains'], feat: ['jungle'], hills: true },
  furs:    { name: 'Furs',    type: 'luxury', f: 1, g: 1, imp: 'camp', on: ['tundra'], feat: ['forest'] },
  ivory:   { name: 'Ivory',   type: 'luxury', p: 1, g: 1, imp: 'camp', on: ['plains', 'grass'], flat: true },
  incense: { name: 'Incense', type: 'luxury', fa: 1, imp: 'plantation', on: ['plains', 'desert'], flat: true },
  salt:    { name: 'Salt',    type: 'luxury', f: 1, g: 1, imp: 'quarry', on: ['plains', 'desert', 'tundra'], flat: true },
  cotton:  { name: 'Cotton',  type: 'luxury', g: 3, imp: 'plantation', on: ['grass', 'plains'], flat: true },
  pearls:  { name: 'Pearls',  type: 'luxury', fa: 1, water: true },
};

const IMPROVEMENTS = {
  farm:       { name: 'Farm', f: 1, tech: null },
  mine:       { name: 'Mine', p: 1, tech: 'mining' },
  quarry:     { name: 'Quarry', p: 1, tech: 'mining' },
  pasture:    { name: 'Pasture', p: 1, tech: 'animal' },
  camp:       { name: 'Camp', g: 1, tech: 'animal' },
  plantation: { name: 'Plantation', g: 1, tech: 'irrigation' },
  well:       { name: 'Oil Well', p: 2, tech: 'refining' },
};

// cls: civ | recon | melee | ranged | anticav | lightcav | heavycav | siege
const UNITS = {
  settler:     { name: 'Settler', cls: 'civ', cost: 80, moves: 2, str: 0, abbr: 'Se' },
  builder:     { name: 'Builder', cls: 'civ', cost: 50, moves: 2, str: 0, abbr: 'Bu' },
  scout:       { name: 'Scout', cls: 'recon', cost: 30, moves: 3, str: 10, abbr: 'Sc', sight: 3 },
  warrior:     { name: 'Warrior', cls: 'melee', cost: 40, moves: 2, str: 20, abbr: 'Wa', upg: 'swordsman' },
  slinger:     { name: 'Slinger', cls: 'ranged', cost: 35, moves: 2, str: 5, rs: 15, range: 1, abbr: 'Sl', upg: 'archer' },
  archer:      { name: 'Archer', cls: 'ranged', cost: 60, moves: 2, str: 15, rs: 25, range: 2, abbr: 'Ar', tech: 'archery', upg: 'crossbow' },
  spearman:    { name: 'Spearman', cls: 'anticav', cost: 65, moves: 2, str: 25, abbr: 'Sp', tech: 'bronze', upg: 'pikeman' },
  heavychariot:{ name: 'Heavy Chariot', cls: 'heavycav', cost: 65, moves: 2, str: 28, abbr: 'HC', tech: 'wheel', upg: 'knight' },
  horseman:    { name: 'Horseman', cls: 'lightcav', cost: 80, moves: 4, str: 36, abbr: 'Ho', tech: 'horseback', res: 'horses', upg: 'cavalry' },
  swordsman:   { name: 'Swordsman', cls: 'melee', cost: 90, moves: 2, str: 35, abbr: 'Sw', tech: 'ironWorking', res: 'iron', upg: 'musketman' },
  catapult:    { name: 'Catapult', cls: 'siege', cost: 120, moves: 2, str: 23, rs: 35, range: 2, abbr: 'Ct', tech: 'mathematics', upg: 'trebuchet' },
  crossbow:    { name: 'Crossbowman', cls: 'ranged', cost: 110, moves: 2, str: 30, rs: 40, range: 2, abbr: 'Cb', tech: 'machinery', upg: 'fieldcannon' },
  pikeman:     { name: 'Pikeman', cls: 'anticav', cost: 160, moves: 2, str: 41, abbr: 'Pk', tech: 'milEng', upg: 'atcrew' },
  knight:      { name: 'Knight', cls: 'heavycav', cost: 180, moves: 4, str: 48, abbr: 'Kn', tech: 'stirrups', res: 'iron', upg: 'tank' },
  trebuchet:   { name: 'Trebuchet', cls: 'siege', cost: 200, moves: 2, str: 30, rs: 45, range: 2, abbr: 'Tb', tech: 'milEng', upg: 'bombard' },
  musketman:   { name: 'Musketman', cls: 'melee', cost: 240, moves: 2, str: 55, abbr: 'Mu', tech: 'gunpowder', res: 'niter', upg: 'infantry' },
  bombard:     { name: 'Bombard', cls: 'siege', cost: 280, moves: 2, str: 43, rs: 55, range: 2, abbr: 'Bo', tech: 'metalCasting', upg: 'artillery' },
  fieldcannon: { name: 'Field Cannon', cls: 'ranged', cost: 330, moves: 2, str: 50, rs: 60, range: 2, abbr: 'FC', tech: 'ballistics', upg: 'machinegun' },
  cavalry:     { name: 'Cavalry', cls: 'lightcav', cost: 330, moves: 5, str: 62, abbr: 'Cv', tech: 'milScience', res: 'horses' },
  infantry:    { name: 'Infantry', cls: 'melee', cost: 430, moves: 2, str: 70, abbr: 'In', tech: 'replaceableParts', upg: 'mechinf' },
  atcrew:      { name: 'AT Crew', cls: 'anticav', cost: 400, moves: 2, str: 70, abbr: 'AT', tech: 'chemistry' },
  artillery:   { name: 'Artillery', cls: 'siege', cost: 430, moves: 2, str: 60, rs: 80, range: 3, abbr: 'Ay', tech: 'steel', upg: 'rocketart' },
  machinegun:  { name: 'Machine Gun', cls: 'ranged', cost: 540, moves: 2, str: 70, rs: 75, range: 2, abbr: 'MG', tech: 'electricity' },
  tank:        { name: 'Tank', cls: 'heavycav', cost: 480, moves: 4, str: 80, abbr: 'Tk', tech: 'combustion', res: 'oil', upg: 'modernarmor' },
  mechinf:     { name: 'Mech. Infantry', cls: 'melee', cost: 650, moves: 3, str: 85, abbr: 'MI', tech: 'satellites' },
  rocketart:   { name: 'Rocket Artillery', cls: 'siege', cost: 680, moves: 3, str: 70, rs: 95, range: 3, abbr: 'RA', tech: 'computers' },
  modernarmor: { name: 'Modern Armor', cls: 'heavycav', cost: 680, moves: 4, str: 90, abbr: 'MA', tech: 'composites', res: 'oil' },
  // --- unique units (replace a base unit for one civilization) ---
  legion:      { name: 'Legion', cls: 'melee', cost: 90, moves: 2, str: 40, abbr: 'Lg', tech: 'ironWorking', res: 'iron', upg: 'musketman', unique: 'rome', replaces: 'swordsman' },
  maryannu:    { name: 'Maryannu Chariot', cls: 'heavycav', cost: 70, moves: 4, str: 34, abbr: 'MC', tech: 'wheel', upg: 'knight', unique: 'egypt', replaces: 'heavychariot' },
  chukonu:     { name: 'Chu-Ko-Nu', cls: 'ranged', cost: 110, moves: 2, str: 30, rs: 45, range: 2, abbr: 'CK', tech: 'machinery', upg: 'fieldcannon', unique: 'china', replaces: 'crossbow' },
  hoplite:     { name: 'Hoplite', cls: 'anticav', cost: 65, moves: 2, str: 30, abbr: 'Hp', tech: 'bronze', upg: 'pikeman', unique: 'greece', replaces: 'spearman' },
  redcoat:     { name: 'Redcoat', cls: 'melee', cost: 250, moves: 2, str: 62, abbr: 'Rc', tech: 'gunpowder', res: 'niter', upg: 'infantry', unique: 'england', replaces: 'musketman' },
  eagle:       { name: 'Eagle Warrior', cls: 'melee', cost: 50, moves: 2, str: 28, abbr: 'EW', upg: 'swordsman', unique: 'aztec', replaces: 'warrior' },
  samurai:     { name: 'Samurai', cls: 'melee', cost: 100, moves: 2, str: 45, abbr: 'Sa', tech: 'ironWorking', res: 'iron', upg: 'musketman', unique: 'japan', replaces: 'swordsman', noDmgPenalty: true },
  keshig:      { name: 'Keshig', cls: 'lightcav', cost: 85, moves: 5, str: 40, abbr: 'Ke', tech: 'horseback', res: 'horses', upg: 'cavalry', unique: 'mongolia', replaces: 'horseman' },
  warchariot:  { name: 'Hittite War Chariot', cls: 'heavycav', cost: 70, moves: 3, str: 36, abbr: 'WC', tech: 'wheel', upg: 'knight', unique: 'hittites', replaces: 'heavychariot' },
  mountainguard:{ name: 'Mountain Guard', cls: 'anticav', cost: 160, moves: 2, str: 46, abbr: 'Gd', tech: 'milEng', upg: 'atcrew', unique: 'tibet', replaces: 'pikeman', ignoreTerrain: true },
  bhayangkara: { name: 'Bhayangkara', cls: 'melee', cost: 240, moves: 2, str: 57, abbr: 'Bh', tech: 'gunpowder', res: 'niter', upg: 'infantry', unique: 'majapahit', replaces: 'musketman', homeBonus: 6 },
  rozvi:       { name: 'Rozvi Spearman', cls: 'anticav', cost: 65, moves: 3, str: 28, abbr: 'Rz', tech: 'bronze', upg: 'pikeman', unique: 'zimbabwe', replaces: 'spearman' },
  chunkey:     { name: 'Chunkey Runner', cls: 'recon', cost: 30, moves: 4, str: 18, abbr: 'CR', sight: 3, unique: 'cahokia', replaces: 'scout' },
  kilwabow:    { name: 'Kilwa Bowman', cls: 'ranged', cost: 60, moves: 3, str: 17, rs: 28, range: 2, abbr: 'KB', tech: 'archery', upg: 'crossbow', unique: 'swahili', replaces: 'archer' },
  mubariz:     { name: 'Mubariz', cls: 'heavycav', cost: 190, moves: 4, str: 53, abbr: 'Mb', tech: 'stirrups', res: 'iron', upg: 'tank', unique: 'timurids', replaces: 'knight' },
};

const DISTRICTS = {
  campus:        { name: 'Campus', tech: 'writing', abbr: 'Ca', color: '#4f82d9', yld: 's', desc: 'Science. +1 per adjacent Mountain, +½ per Rainforest and district.' },
  holy:          { name: 'Holy Site', tech: 'astrology', abbr: 'HS', color: '#e6d27c', yld: 'fa', desc: 'Faith. +1 per adjacent Mountain, +½ per Woods and district.' },
  commercial:    { name: 'Commercial Hub', tech: 'currency', abbr: 'CH', color: '#d8a632', yld: 'g', desc: 'Gold. +2 next to a Harbor, +1 next to water, +½ per district.' },
  harbor:        { name: 'Harbor', tech: 'sailing', abbr: 'Hb', color: '#3a9ac6', yld: 'g', water: true, desc: 'Gold. Built on coast. +2 next to the City Center, +1 per sea resource.' },
  industrial:    { name: 'Industrial Zone', tech: 'apprenticeship', abbr: 'IZ', color: '#cf7431', yld: 'p', desc: 'Production. +1 per adjacent Mine or Quarry, +2 per Aqueduct, +½ per district.' },
  theater:       { name: 'Theater Square', civic: 'dramaPoetry', abbr: 'TS', color: '#a563c8', yld: 'c', desc: 'Culture. +1 per Wonder in the city, +2 next to an Entertainment Complex.' },
  encampment:    { name: 'Encampment', tech: 'bronze', abbr: 'En', color: '#b8403d', yld: null, desc: 'Military buildings. Units trained here gain experience.' },
  entertainment: { name: 'Entertainment Complex', civic: 'gamesRecreation', abbr: 'EC', color: '#57bf86', yld: null, desc: 'Happiness buildings: Arena, Zoo, Stadium.' },
  aqueduct:      { name: 'Aqueduct', tech: 'engineering', abbr: 'Aq', color: '#86c0dd', yld: null, noCount: true, adjCenter: true, housing: 4, desc: '+4 Housing. Must touch the City Center. Does not count toward the district limit.' },
  spaceport:     { name: 'Spaceport', tech: 'rocketry', abbr: 'SP', color: '#a9b2bd', yld: null, flatOnly: true, noCount: true, desc: 'Launches space projects for a Science Victory. Does not count toward the district limit.' },
};

const BUILDINGS = {
  monument:     { name: 'Monument', cost: 60, c: 2, desc: '+2 Culture' },
  granary:      { name: 'Granary', cost: 65, f: 1, housing: 2, tech: 'pottery', desc: '+1 Food, +2 Housing' },
  walls:        { name: 'Ancient Walls', cost: 80, tech: 'masonry', hp: 100, def: 6, desc: '+100 City HP, +6 City Strength' },
  shrine:       { name: 'Shrine', district: 'holy', cost: 70, fa: 2, tech: 'astrology', desc: '+2 Faith' },
  temple:       { name: 'Temple', district: 'holy', cost: 120, fa: 4, happy: 1, civic: 'theology', req: 'shrine', desc: '+4 Faith, +1 Happiness' },
  library:      { name: 'Library', district: 'campus', cost: 90, s: 2, tech: 'writing', desc: '+2 Science' },
  university:   { name: 'University', district: 'campus', cost: 250, s: 4, housing: 1, tech: 'education', req: 'library', desc: '+4 Science, +1 Housing' },
  researchlab:  { name: 'Research Lab', district: 'campus', cost: 480, s: 6, tech: 'chemistry', req: 'university', desc: '+6 Science' },
  market:       { name: 'Market', district: 'commercial', cost: 120, g: 3, tech: 'currency', desc: '+3 Gold' },
  bank:         { name: 'Bank', district: 'commercial', cost: 290, g: 5, tech: 'banking', req: 'market', desc: '+5 Gold' },
  stockexchange:{ name: 'Stock Exchange', district: 'commercial', cost: 480, g: 7, tech: 'economics', req: 'bank', desc: '+7 Gold' },
  lighthouse:   { name: 'Lighthouse', district: 'harbor', cost: 120, f: 2, g: 1, housing: 1, tech: 'sailing', desc: '+2 Food, +1 Gold, +1 Housing' },
  shipyard:     { name: 'Shipyard', district: 'harbor', cost: 290, p: 3, g: 1, tech: 'astronomy', req: 'lighthouse', desc: '+3 Production, +1 Gold' },
  workshop:     { name: 'Workshop', district: 'industrial', cost: 195, p: 3, tech: 'apprenticeship', desc: '+3 Production' },
  factory:      { name: 'Factory', district: 'industrial', cost: 330, p: 4, tech: 'industrialization', req: 'workshop', desc: '+4 Production' },
  powerplant:   { name: 'Power Plant', district: 'industrial', cost: 480, p: 5, tech: 'electricity', req: 'factory', desc: '+5 Production' },
  amphitheater: { name: 'Amphitheater', district: 'theater', cost: 150, c: 2, civic: 'dramaPoetry', desc: '+2 Culture' },
  museum:       { name: 'Art Museum', district: 'theater', cost: 290, c: 3, civic: 'humanism', req: 'amphitheater', desc: '+3 Culture' },
  broadcast:    { name: 'Broadcast Center', district: 'theater', cost: 480, c: 5, tech: 'radio', req: 'museum', desc: '+5 Culture' },
  barracks:     { name: 'Barracks', district: 'encampment', cost: 90, p: 1, xp: 25, tech: 'bronze', desc: '+1 Production. New land units start with a promotion.' },
  armory:       { name: 'Armory', district: 'encampment', cost: 195, p: 2, xp: 25, tech: 'milEng', req: 'barracks', desc: '+2 Production. More starting experience.' },
  arena:        { name: 'Arena', district: 'entertainment', cost: 150, happy: 3, civic: 'gamesRecreation', desc: '+3 Happiness' },
  zoo:          { name: 'Zoo', district: 'entertainment', cost: 445, happy: 3, civic: 'naturalHistory', req: 'arena', desc: '+3 Happiness' },
  stadium:      { name: 'Stadium', district: 'entertainment', cost: 660, happy: 4, civic: 'massMedia', req: 'zoo', desc: '+4 Happiness' },
  // --- unique buildings ---
  dzong:        { name: 'Dzong', cost: 80, tech: 'masonry', hp: 100, def: 8, fa: 2, unique: 'tibet', replaces: 'walls', desc: '+100 City HP, +8 City Strength, +2 Faith' },
  candi:        { name: 'Candi', district: 'holy', cost: 70, fa: 3, c: 1, tech: 'astrology', unique: 'majapahit', replaces: 'shrine', desc: '+3 Faith, +1 Culture' },
  mound:        { name: 'Earthwork Mound', cost: 65, f: 2, fa: 1, housing: 3, tech: 'pottery', unique: 'cahokia', replaces: 'granary', desc: '+2 Food, +1 Faith, +3 Housing' },
  stonetown:    { name: 'Stone Town', district: 'commercial', cost: 120, g: 5, c: 1, tech: 'currency', unique: 'swahili', replaces: 'market', desc: '+5 Gold, +1 Culture' },
  ulughbeg:     { name: 'Ulugh Beg Observatory', district: 'campus', cost: 250, s: 6, housing: 1, tech: 'education', req: 'library', unique: 'timurids', replaces: 'university', desc: '+6 Science, +1 Housing' },
  smeltery:     { name: 'Smelting Works', district: 'industrial', cost: 195, p: 4, tech: 'apprenticeship', unique: 'hittites', replaces: 'workshop', desc: '+4 Production' },
  hillfort:     { name: 'Great Enclosure', cost: 60, tech: 'masonry', hp: 100, def: 6, c: 2, unique: 'zimbabwe', replaces: 'walls', desc: '+100 City HP, +6 City Strength, +2 Culture' },
};

const WONDERS = {
  stonehenge:    { name: 'Stonehenge', tech: 'astrology', cost: 180, fa: 4, desc: '+4 Faith' },
  pyramids:      { name: 'Pyramids', tech: 'masonry', cost: 220, p: 2, desc: '+2 Production. New Builders get +1 charge.' },
  hanging:       { name: 'Hanging Gardens', tech: 'irrigation', cost: 180, f: 2, desc: '+2 Food here, +15% growth in every city' },
  oracle:        { name: 'Oracle', civic: 'mysticism', cost: 290, c: 2, fa: 2, desc: '+2 Culture, +2 Faith' },
  colossus:      { name: 'Colossus', tech: 'currency', cost: 290, g: 4, coastal: true, desc: '+4 Gold. Coastal city only.' },
  greatLibrary:  { name: 'Great Library', civic: 'recordedHistory', cost: 400, s: 3, desc: '+3 Science. Grants every Ancient and Classical Eureka.' },
  colosseum:     { name: 'Colosseum', civic: 'gamesRecreation', cost: 400, c: 2, happy: 4, desc: '+4 Happiness, +2 Culture' },
  terracotta:    { name: 'Terracotta Army', tech: 'construction', cost: 400, desc: 'Every current land unit gains a promotion.' },
  greatWall:     { name: 'Great Wall', tech: 'engineering', cost: 400, c: 1, desc: '+4 Strength for all your cities, +1 Culture' },
  hagiaSophia:   { name: 'Hagia Sophia', civic: 'theology', cost: 500, fa: 4, happy: 2, desc: '+4 Faith, +2 Happiness' },
  forbiddenCity: { name: 'Forbidden City', civic: 'divineRight', cost: 700, c: 2, desc: '+1 Wildcard policy slot' },
  oxford:        { name: 'Oxford University', tech: 'scientificTheory', cost: 1100, s: 6, desc: '+6 Science and 2 free technologies' },
  bigBen:        { name: 'Big Ben', tech: 'economics', cost: 1200, g: 8, desc: '+8 Gold, +10% Gold empire-wide' },
  eiffel:        { name: 'Eiffel Tower', tech: 'steel', cost: 1500, c: 3, happy: 5, desc: '+5 Happiness, +3 Culture' },
  broadway:      { name: 'Broadway', civic: 'massMedia', cost: 1600, c: 8, desc: '+8 Culture' },
};

const PROJECTS = {
  satellite: { name: 'Launch Earth Satellite', tech: 'satellites', cost: 600, desc: 'First step of the space race.' },
  moon:      { name: 'Launch Moon Landing', tech: 'satellites', cost: 800, req: 'satellite', desc: 'Second step of the space race.' },
  mars:      { name: 'Launch Mars Colony', tech: 'spaceExploration', cost: 1000, req: 'moon', desc: 'Completing this wins a Science Victory.' },
};

// Boost trigger kinds: imp, impRes, kills, barbKills, meet, explored, lux, districts,
// district, building, buildings, unitCls, units, civic, tech, pop, cities, coastal,
// pantheon, wonders, project.
const TECHS = {
  pottery:          { name: 'Pottery', era: 0, cost: 25, req: [] },
  animal:           { name: 'Animal Husbandry', era: 0, cost: 25, req: [], desc: 'Reveals Horses.' },
  mining:           { name: 'Mining', era: 0, cost: 25, req: [], desc: 'Builders can harvest Woods.' },
  sailing:          { name: 'Sailing', era: 0, cost: 50, req: [], boost: { k: 'coastal', n: 1, d: 'Found a coastal city' } },
  astrology:        { name: 'Astrology', era: 0, cost: 50, req: [], boost: { k: 'explored', n: 70, d: 'Explore 70 tiles' } },
  irrigation:       { name: 'Irrigation', era: 0, cost: 50, req: ['pottery'], boost: { k: 'imp', v: 'farm', n: 2, d: 'Build 2 Farms' } },
  archery:          { name: 'Archery', era: 0, cost: 50, req: ['animal'], boost: { k: 'kills', n: 1, d: 'Win a battle' } },
  writing:          { name: 'Writing', era: 0, cost: 50, req: ['pottery'], boost: { k: 'meet', n: 1, d: 'Meet another civilization' } },
  masonry:          { name: 'Masonry', era: 0, cost: 80, req: ['mining'], boost: { k: 'imp', v: 'quarry', n: 1, d: 'Build a Quarry' } },
  bronze:           { name: 'Bronze Working', era: 0, cost: 80, req: ['mining'], desc: 'Reveals Iron. Builders can harvest Rainforest.', boost: { k: 'barbKills', n: 1, d: 'Defeat a barbarian unit' } },
  wheel:            { name: 'The Wheel', era: 0, cost: 80, req: ['mining'], boost: { k: 'imp', v: 'mine', n: 2, d: 'Build 2 Mines' } },
  currency:         { name: 'Currency', era: 1, cost: 120, req: ['writing'], boost: { k: 'lux', n: 2, d: 'Own 2 kinds of luxury resource' } },
  horseback:        { name: 'Horseback Riding', era: 1, cost: 120, req: ['animal'], boost: { k: 'imp', v: 'pasture', n: 1, d: 'Build a Pasture' } },
  ironWorking:      { name: 'Iron Working', era: 1, cost: 120, req: ['bronze'], boost: { k: 'impRes', v: 'iron', n: 1, d: 'Mine an Iron resource' } },
  mathematics:      { name: 'Mathematics', era: 1, cost: 200, req: ['currency'], boost: { k: 'districts', n: 3, d: 'Build 3 districts' } },
  construction:     { name: 'Construction', era: 1, cost: 200, req: ['masonry', 'horseback'], boost: { k: 'buildings', n: 4, d: 'Construct 4 buildings' } },
  engineering:      { name: 'Engineering', era: 1, cost: 200, req: ['wheel'], boost: { k: 'building', v: 'walls', n: 1, d: 'Build Ancient Walls' } },
  apprenticeship:   { name: 'Apprenticeship', era: 2, cost: 290, req: ['currency', 'mining'], boost: { k: 'imp', v: 'mine', n: 3, d: 'Build 3 Mines' } },
  machinery:        { name: 'Machinery', era: 2, cost: 290, req: ['ironWorking', 'engineering'], boost: { k: 'unitCls', v: 'ranged', n: 3, d: 'Own 3 ranged units' } },
  education:        { name: 'Education', era: 2, cost: 390, req: ['apprenticeship', 'mathematics'], boost: { k: 'building', v: 'library', n: 2, d: 'Build 2 Libraries' } },
  stirrups:         { name: 'Stirrups', era: 2, cost: 390, req: ['horseback'], boost: { k: 'civic', v: 'feudalism', d: 'Adopt Feudalism' } },
  milEng:           { name: 'Military Engineering', era: 2, cost: 390, req: ['construction'], desc: 'Reveals Niter.', boost: { k: 'building', v: 'barracks', n: 1, d: 'Build Barracks' } },
  astronomy:        { name: 'Astronomy', era: 3, cost: 540, req: ['education'], boost: { k: 'building', v: 'university', n: 1, d: 'Build a University' } },
  banking:          { name: 'Banking', era: 3, cost: 540, req: ['education', 'stirrups'], boost: { k: 'civic', v: 'guilds', d: 'Adopt Guilds' } },
  gunpowder:        { name: 'Gunpowder', era: 3, cost: 540, req: ['apprenticeship', 'milEng'], boost: { k: 'building', v: 'armory', n: 1, d: 'Build an Armory' } },
  printing:         { name: 'Printing', era: 3, cost: 540, req: ['machinery'], boost: { k: 'building', v: 'workshop', n: 2, d: 'Build 2 Workshops' } },
  metalCasting:     { name: 'Metal Casting', era: 3, cost: 660, req: ['gunpowder'], boost: { k: 'unitCls', v: 'siege', n: 2, d: 'Own 2 siege units' } },
  industrialization:{ name: 'Industrialization', era: 4, cost: 900, req: ['banking', 'printing'], desc: 'Reveals Coal.', boost: { k: 'building', v: 'workshop', n: 3, d: 'Build 3 Workshops' } },
  scientificTheory: { name: 'Scientific Theory', era: 4, cost: 900, req: ['astronomy'], boost: { k: 'civic', v: 'enlightenment', d: 'Adopt The Enlightenment' } },
  ballistics:       { name: 'Ballistics', era: 4, cost: 1000, req: ['metalCasting'], boost: { k: 'building', v: 'walls', n: 3, d: 'Build 3 sets of walls' } },
  milScience:       { name: 'Military Science', era: 4, cost: 1000, req: ['stirrups', 'metalCasting'], boost: { k: 'kills', n: 8, d: 'Win 8 battles' } },
  economics:        { name: 'Economics', era: 4, cost: 1000, req: ['banking'], boost: { k: 'building', v: 'bank', n: 2, d: 'Build 2 Banks' } },
  electricity:      { name: 'Electricity', era: 5, cost: 1300, req: ['scientificTheory', 'industrialization'], boost: { k: 'building', v: 'factory', n: 1, d: 'Build a Factory' } },
  chemistry:        { name: 'Chemistry', era: 5, cost: 1300, req: ['scientificTheory'], boost: { k: 'building', v: 'university', n: 3, d: 'Build 3 Universities' } },
  refining:         { name: 'Refining', era: 5, cost: 1300, req: ['chemistry'], desc: 'Reveals Oil.', boost: { k: 'imp', v: 'mine', n: 6, d: 'Build 6 Mines' } },
  replaceableParts: { name: 'Replaceable Parts', era: 5, cost: 1450, req: ['economics', 'milScience'], boost: { k: 'unitCls', v: 'melee', n: 4, d: 'Own 4 melee units' } },
  steel:            { name: 'Steel', era: 5, cost: 1450, req: ['industrialization', 'ballistics'], boost: { k: 'building', v: 'factory', n: 2, d: 'Build 2 Factories' } },
  radio:            { name: 'Radio', era: 6, cost: 1700, req: ['electricity'], boost: { k: 'building', v: 'museum', n: 1, d: 'Build an Art Museum' } },
  combustion:       { name: 'Combustion', era: 6, cost: 1700, req: ['refining', 'steel'], boost: { k: 'impRes', v: 'oil', n: 1, d: 'Build an Oil Well' } },
  rocketry:         { name: 'Rocketry', era: 6, cost: 1900, req: ['radio', 'chemistry'], boost: { k: 'civic', v: 'ideology', d: 'Adopt Ideology' } },
  computers:        { name: 'Computers', era: 7, cost: 2100, req: ['rocketry'], boost: { k: 'building', v: 'researchlab', n: 2, d: 'Build 2 Research Labs' } },
  satellites:       { name: 'Satellites', era: 7, cost: 2200, req: ['rocketry', 'combustion'], boost: { k: 'district', v: 'spaceport', n: 1, d: 'Build a Spaceport' } },
  composites:       { name: 'Composites', era: 7, cost: 2300, req: ['combustion', 'computers'], boost: { k: 'unitCls', v: 'heavycav', n: 2, d: 'Own 2 heavy cavalry units' } },
  spaceExploration: { name: 'Space Exploration', era: 7, cost: 2600, req: ['satellites', 'computers'], boost: { k: 'project', v: 'satellite', d: 'Launch an Earth Satellite' } },
};

const CIVICS = {
  codeOfLaws:        { name: 'Code of Laws', era: 0, cost: 20, req: [] },
  craftsmanship:     { name: 'Craftsmanship', era: 0, cost: 40, req: ['codeOfLaws'], boost: { k: 'imp', v: '*', n: 3, d: 'Build 3 improvements' } },
  foreignTrade:      { name: 'Foreign Trade', era: 0, cost: 40, req: ['codeOfLaws'], boost: { k: 'explored', n: 45, d: 'Explore 45 tiles' } },
  earlyEmpire:       { name: 'Early Empire', era: 0, cost: 70, req: ['foreignTrade'], boost: { k: 'pop', n: 6, d: 'Reach 6 total population' } },
  mysticism:         { name: 'Mysticism', era: 0, cost: 50, req: ['foreignTrade'], boost: { k: 'pantheon', d: 'Found a Pantheon' } },
  militaryTradition: { name: 'Military Tradition', era: 0, cost: 50, req: ['craftsmanship'], boost: { k: 'kills', n: 1, d: 'Win a battle' } },
  stateWorkforce:    { name: 'State Workforce', era: 0, cost: 70, req: ['craftsmanship'], boost: { k: 'districts', n: 1, d: 'Build any district' } },
  politicalPhilosophy:{ name: 'Political Philosophy', era: 1, cost: 110, req: ['stateWorkforce', 'earlyEmpire'], boost: { k: 'meet', n: 2, d: 'Meet 2 civilizations' } },
  gamesRecreation:   { name: 'Games and Recreation', era: 1, cost: 110, req: ['stateWorkforce'], boost: { k: 'tech', v: 'construction', d: 'Research Construction' } },
  dramaPoetry:       { name: 'Drama and Poetry', era: 1, cost: 110, req: ['earlyEmpire'], boost: { k: 'wonders', n: 1, d: 'Build a Wonder' } },
  theology:          { name: 'Theology', era: 1, cost: 120, req: ['dramaPoetry', 'mysticism'], boost: { k: 'building', v: 'shrine', n: 2, d: 'Build 2 Shrines' } },
  militaryTraining:  { name: 'Military Training', era: 1, cost: 120, req: ['militaryTradition', 'gamesRecreation'], boost: { k: 'building', v: 'barracks', n: 1, d: 'Build Barracks' } },
  defensiveTactics:  { name: 'Defensive Tactics', era: 1, cost: 175, req: ['gamesRecreation', 'politicalPhilosophy'], boost: { k: 'building', v: 'walls', n: 1, d: 'Build Ancient Walls' } },
  recordedHistory:   { name: 'Recorded History', era: 1, cost: 175, req: ['politicalPhilosophy', 'dramaPoetry'], boost: { k: 'building', v: 'library', n: 2, d: 'Build 2 Libraries' } },
  feudalism:         { name: 'Feudalism', era: 2, cost: 275, req: ['defensiveTactics'], boost: { k: 'imp', v: 'farm', n: 6, d: 'Build 6 Farms' } },
  civilService:      { name: 'Civil Service', era: 2, cost: 275, req: ['defensiveTactics', 'recordedHistory'], boost: { k: 'pop', n: 18, d: 'Reach 18 total population' } },
  mercenaries:       { name: 'Mercenaries', era: 2, cost: 290, req: ['militaryTraining', 'feudalism'], boost: { k: 'units', n: 8, d: 'Own 8 military units' } },
  divineRight:       { name: 'Divine Right', era: 2, cost: 290, req: ['civilService', 'theology'], boost: { k: 'building', v: 'temple', n: 2, d: 'Build 2 Temples' } },
  guilds:            { name: 'Guilds', era: 2, cost: 385, req: ['feudalism', 'civilService'], boost: { k: 'building', v: 'market', n: 2, d: 'Build 2 Markets' } },
  exploration:       { name: 'Exploration', era: 3, cost: 400, req: ['mercenaries', 'guilds'], boost: { k: 'explored', n: 250, d: 'Explore 250 tiles' } },
  reformedChurch:    { name: 'Reformed Church', era: 3, cost: 400, req: ['divineRight'], boost: { k: 'building', v: 'temple', n: 3, d: 'Build 3 Temples' } },
  humanism:          { name: 'Humanism', era: 3, cost: 540, req: ['guilds', 'divineRight'], boost: { k: 'wonders', n: 2, d: 'Build 2 Wonders' } },
  diplomaticService: { name: 'Diplomatic Service', era: 3, cost: 540, req: ['guilds'], boost: { k: 'meet', n: 3, d: 'Meet 3 civilizations' } },
  mercantilism:      { name: 'Mercantilism', era: 3, cost: 655, req: ['humanism'], boost: { k: 'building', v: 'bank', n: 1, d: 'Build a Bank' } },
  enlightenment:     { name: 'The Enlightenment', era: 3, cost: 655, req: ['diplomaticService', 'humanism'], boost: { k: 'building', v: 'university', n: 2, d: 'Build 2 Universities' } },
  civilEngineering:  { name: 'Civil Engineering', era: 4, cost: 920, req: ['mercantilism'], boost: { k: 'districts', n: 10, d: 'Build 10 districts' } },
  nationalism:       { name: 'Nationalism', era: 4, cost: 920, req: ['enlightenment'], boost: { k: 'units', n: 12, d: 'Own 12 military units' } },
  naturalHistory:    { name: 'Natural History', era: 4, cost: 870, req: ['humanism'], boost: { k: 'building', v: 'museum', n: 1, d: 'Build an Art Museum' } },
  urbanization:      { name: 'Urbanization', era: 4, cost: 1060, req: ['civilEngineering'], boost: { k: 'pop', n: 60, d: 'Reach 60 total population' } },
  massMedia:         { name: 'Mass Media', era: 5, cost: 1410, req: ['urbanization'], boost: { k: 'tech', v: 'radio', d: 'Research Radio' } },
  ideology:          { name: 'Ideology', era: 5, cost: 1640, req: ['nationalism', 'urbanization'] },
  suffrage:          { name: 'Suffrage', era: 5, cost: 1640, req: ['ideology'] },
  classStruggle:     { name: 'Class Struggle', era: 5, cost: 1640, req: ['ideology'] },
  totalitarianism:   { name: 'Totalitarianism', era: 5, cost: 1640, req: ['ideology'] },
};

// slots: [military, economic, diplomatic, wildcard]
const GOVERNMENTS = {
  chiefdom:          { name: 'Chiefdom', civic: 'codeOfLaws', tier: 0, slots: [1, 1, 0, 0], desc: 'No bonus.' },
  autocracy:         { name: 'Autocracy', civic: 'politicalPhilosophy', tier: 1, slots: [1, 1, 1, 1], desc: '+2 to every yield in the capital.' },
  oligarchy:         { name: 'Oligarchy', civic: 'politicalPhilosophy', tier: 1, slots: [1, 1, 1, 1], desc: '+4 Strength for melee and anti-cavalry units.' },
  republic:          { name: 'Classical Republic', civic: 'politicalPhilosophy', tier: 1, slots: [0, 2, 1, 1], desc: '+3 Happiness.' },
  monarchy:          { name: 'Monarchy', civic: 'divineRight', tier: 2, slots: [3, 1, 1, 1], desc: '+2 Housing in every city.' },
  merchantRepublic:  { name: 'Merchant Republic', civic: 'exploration', tier: 2, slots: [1, 2, 2, 1], desc: '+15% Gold.' },
  theocracy:         { name: 'Theocracy', civic: 'reformedChurch', tier: 2, slots: [2, 2, 1, 1], desc: '+15% Faith. Buy land units with Faith.' },
  democracy:         { name: 'Democracy', civic: 'suffrage', tier: 3, slots: [1, 3, 2, 2], desc: '+10% Gold and Science.' },
  communism:         { name: 'Communism', civic: 'classStruggle', tier: 3, slots: [3, 3, 1, 1], desc: '+15% Production.' },
  fascism:           { name: 'Fascism', civic: 'totalitarianism', tier: 3, slots: [4, 1, 1, 2], desc: '+5 Strength for all units.' },
};

const SLOT_NAMES = ['Military', 'Economic', 'Diplomatic', 'Wildcard'];

// slot: 0 military, 1 economic, 2 diplomatic, 3 wildcard-only
const POLICIES = {
  discipline:        { name: 'Discipline', slot: 0, civic: 'codeOfLaws', desc: '+5 Strength against barbarians.' },
  agoge:             { name: 'Agoge', slot: 0, civic: 'craftsmanship', desc: '+50% Production toward melee, ranged and anti-cavalry units.' },
  maneuver:          { name: 'Maneuver', slot: 0, civic: 'militaryTradition', desc: '+50% Production toward cavalry units.' },
  conscription:      { name: 'Conscription', slot: 0, civic: 'stateWorkforce', desc: '4 more units are upkeep-free.' },
  bastions:          { name: 'Bastions', slot: 0, civic: 'militaryTraining', desc: '+6 City Strength.' },
  limes:             { name: 'Limes', slot: 0, civic: 'defensiveTactics', desc: '+100% Production toward walls.' },
  professionalArmy:  { name: 'Professional Army', slot: 0, civic: 'mercenaries', desc: 'Unit upgrades cost 50% less Gold.' },
  leveeEnMasse:      { name: 'Levée en Masse', slot: 0, civic: 'nationalism', desc: '+3 Strength for all units.' },
  godKing:           { name: 'God King', slot: 1, civic: 'codeOfLaws', desc: '+1 Faith and +1 Gold in the capital.' },
  urbanPlanning:     { name: 'Urban Planning', slot: 1, civic: 'codeOfLaws', desc: '+1 Production in every city.' },
  ilkum:             { name: 'Ilkum', slot: 1, civic: 'craftsmanship', desc: '+30% Production toward Builders.' },
  caravansaries:     { name: 'Caravansaries', slot: 1, civic: 'foreignTrade', desc: '+2 Gold in every city.' },
  colonization:      { name: 'Colonization', slot: 1, civic: 'earlyEmpire', desc: '+50% Production toward Settlers.' },
  landSurveyors:     { name: 'Land Surveyors', slot: 1, civic: 'earlyEmpire', desc: 'Tiles cost 30% less Gold.' },
  naturalPhilosophy: { name: 'Natural Philosophy', slot: 1, civic: 'recordedHistory', desc: '+100% Campus adjacency.' },
  scripture:         { name: 'Scripture', slot: 1, civic: 'theology', desc: '+100% Holy Site adjacency.' },
  serfdom:           { name: 'Serfdom', slot: 1, civic: 'feudalism', desc: 'New Builders get +2 charges.' },
  meritocracy:       { name: 'Meritocracy', slot: 1, civic: 'civilService', desc: '+1 Culture per district.' },
  townCharters:      { name: 'Town Charters', slot: 1, civic: 'guilds', desc: '+100% Commercial Hub adjacency.' },
  craftsmen:         { name: 'Craftsmen', slot: 1, civic: 'guilds', desc: '+100% Industrial Zone adjacency.' },
  freeMarket:        { name: 'Free Market', slot: 1, civic: 'mercantilism', desc: '+15% Gold.' },
  rationalism:       { name: 'Rationalism', slot: 1, civic: 'enlightenment', desc: '+15% Science.' },
  publicWorks:       { name: 'Public Works', slot: 1, civic: 'civilEngineering', desc: '+30% Production toward districts.' },
  urbanHousing:      { name: 'Urban Housing', slot: 1, civic: 'urbanization', desc: '+3 Housing in every city.' },
  charismatic:       { name: 'Charismatic Leader', slot: 2, civic: 'politicalPhilosophy', desc: '+3 Happiness.' },
  embassies:         { name: 'Embassies', slot: 2, civic: 'diplomaticService', desc: '+1 Science and +1 Culture per civilization met.' },
  raj:               { name: 'Raj', slot: 2, civic: 'mercantilism', desc: '+2 Gold and +1 Culture in every city.' },
  inspiration:       { name: 'Inspiration', slot: 3, civic: 'mysticism', desc: '+2 Science in the capital.' },
  revelation:        { name: 'Revelation', slot: 3, civic: 'mysticism', desc: '+2 Faith in the capital.' },
  goldenAgeFest:     { name: 'Festivals', slot: 3, civic: 'humanism', desc: '+50% Golden Age points.' },
};

const PANTHEONS = {
  fertility:    { name: 'Fertility Rites', desc: '+10% growth in every city.' },
  godForge:     { name: 'God of the Forge', desc: '+25% Production toward military units.' },
  sacredGroves: { name: 'Sacred Groves', desc: 'Worked Woods tiles give +1 Faith.' },
  godSea:       { name: 'God of the Sea', desc: 'Worked Coast tiles give +1 Production.' },
  goddessHunt:  { name: 'Goddess of the Hunt', desc: 'Camps give +1 Food and +1 Faith.' },
  stoneCircles: { name: 'Stone Circles', desc: 'Quarries give +2 Faith.' },
  danceAurora:  { name: 'Dance of the Aurora', desc: 'Worked Tundra tiles give +1 Faith.' },
  monumentGods: { name: 'Monument to the Gods', desc: '+15% Production toward Wonders.' },
  godWar:       { name: 'God of War', desc: 'Earn Faith equal to the strength of every unit you defeat.' },
  cityPatron:   { name: 'City Patron Goddess', desc: '+25% Production toward districts in cities with no district yet.' },
};

const FOUNDER_BELIEFS = {
  tithe:        { name: 'Tithe', desc: '+1 Gold for every 4 population.' },
  churchProp:   { name: 'Church Property', desc: '+2 Gold in every city.' },
  worldChurch:  { name: 'World Church', desc: '+1 Culture in every city.' },
  pilgrimage:   { name: 'Pilgrimage', desc: '+2 Faith in every city.' },
};

const FOLLOWER_BELIEFS = {
  feedWorld:    { name: 'Feed the World', desc: 'Shrines and Temples give +2 Food.' },
  workEthic:    { name: 'Work Ethic', desc: '+10% Production in every city.' },
  choralMusic:  { name: 'Choral Music', desc: 'Shrines and Temples give +2 Culture.' },
  jesuit:       { name: 'Jesuit Education', desc: 'Holy Sites give +2 Science.' },
  zen:          { name: 'Zen Meditation', desc: '+1 Happiness per city.' },
};

const RELIGION_NAMES = ['Buddhism', 'Christianity', 'Hinduism', 'Islam', 'Judaism', 'Taoism', 'Zoroastrianism', 'Shinto', 'Tengrism', 'Bön', 'Kejawen', 'Mwari', 'Sikhism', 'Jainism', 'Hellenism'];

// ---------------------------------------------------------------------------
// Civilizations. `isNew` marks civs that appear in neither Civ V nor Civ VI.
// ---------------------------------------------------------------------------
const CIVS = {
  rome: { name: 'Rome', adj: 'Roman', leader: 'Trajan', color: '#8a2433', text: '#f4dfa6', aggr: 0.6,
    ability: 'All Roads Lead to Rome', abilityDesc: 'Every new city starts with a free Monument.',
    mods: { freeMonument: true }, uu: 'legion',
    cities: ['Roma', 'Antium', 'Cumae', 'Neapolis', 'Ravenna', 'Arretium', 'Mediolanum', 'Arpinum', 'Circei', 'Setia', 'Satricum', 'Ardea'] },
  egypt: { name: 'Egypt', adj: 'Egyptian', leader: 'Cleopatra', color: '#e2c044', text: '#2b3f7a', aggr: 0.4,
    ability: 'Iteru', abilityDesc: '+15% Production toward districts and Wonders.',
    mods: { districtProd: 0.15, wonderProd: 0.15 }, uu: 'maryannu',
    cities: ['Thebes', 'Memphis', 'Heliopolis', 'Elephantine', 'Alexandria', 'Pi-Ramesses', 'Giza', 'Byblos', 'Akhetaten', 'Hieraconpolis', 'Abydos', 'Asyut'] },
  china: { name: 'China', adj: 'Chinese', leader: 'Qin Shi Huang', color: '#3d9a55', text: '#f3e28a', aggr: 0.4,
    ability: 'Dynastic Cycle', abilityDesc: 'Eurekas and Inspirations give 50% instead of 40%. Builders get +1 charge.',
    mods: { boostPct: 0.5, builderCharges: 1 }, uu: 'chukonu',
    cities: ['Xian', 'Beijing', 'Nanjing', 'Shanghai', 'Guangzhou', 'Chengdu', 'Hangzhou', 'Wuhan', 'Luoyang', 'Kaifeng', 'Suzhou', 'Datong'] },
  greece: { name: 'Greece', adj: 'Greek', leader: 'Pericles', color: '#4a78c2', text: '#f1f4fb', aggr: 0.5,
    ability: "Plato's Republic", abilityDesc: '+1 Wildcard policy slot in any government.',
    mods: { wildcard: 1 }, uu: 'hoplite',
    cities: ['Athens', 'Sparta', 'Corinth', 'Argos', 'Knossos', 'Mycenae', 'Pharsalos', 'Ephesus', 'Delphi', 'Rhodes', 'Eretria', 'Pella'] },
  england: { name: 'England', adj: 'English', leader: 'Victoria', color: '#d6463a', text: '#fbf3e4', aggr: 0.5,
    ability: 'Workshop of the World', abilityDesc: 'Industrial Zone adjacency doubled. Mines on Iron and Coal give +2 Production.',
    mods: { industrialAdj: 2, stratMine: 2 }, uu: 'redcoat',
    cities: ['London', 'York', 'Nottingham', 'Hastings', 'Canterbury', 'Coventry', 'Warwick', 'Newcastle', 'Oxford', 'Liverpool', 'Dover', 'Brighton'] },
  aztec: { name: 'Aztec', adj: 'Aztec', leader: 'Montezuma', color: '#23b3a6', text: '#842020', aggr: 0.8,
    ability: 'Gifts for the Tlatoani', abilityDesc: 'Each kind of luxury resource gives +5 Happiness instead of +4.',
    mods: { luxHappy: 1 }, uu: 'eagle',
    cities: ['Tenochtitlan', 'Texcoco', 'Tlatelolco', 'Tlacopan', 'Xochimilco', 'Chalco', 'Cholula', 'Tula', 'Coyoacan', 'Tlaxcala', 'Culhuacan', 'Azcapotzalco'] },
  japan: { name: 'Japan', adj: 'Japanese', leader: 'Hojo Tokimune', color: '#ecebe6', text: '#b01e2d', aggr: 0.6,
    ability: 'Meiji Restoration', abilityDesc: 'Districts get +1 adjacency (instead of +½) from each adjacent district.',
    mods: { districtAdj: 1 }, uu: 'samurai',
    cities: ['Kyoto', 'Osaka', 'Tokyo', 'Satsuma', 'Kagoshima', 'Nara', 'Nagoya', 'Sendai', 'Kamakura', 'Hiroshima', 'Nagasaki', 'Fukuoka'] },
  mongolia: { name: 'Mongolia', adj: 'Mongol', leader: 'Genghis Khan', color: '#6b4aa3', text: '#f0d27a', aggr: 0.9,
    ability: 'Örtöö', abilityDesc: 'Cavalry units get +1 Movement and +3 Strength.',
    mods: { cavMoves: 1, cavStr: 3 }, uu: 'keshig',
    cities: ['Karakorum', 'Beshbalik', 'Turfan', 'Hovd', 'Uliastai', 'Aksu', 'Ghazni', 'Kashgar', 'Ulaanbaatar', 'Almaliq', 'Otrar', 'Olgii'] },
  // ---- civilizations that appear in neither Civilization V nor VI ----
  hittites: { name: 'Hittites', adj: 'Hittite', leader: 'Šuppiluliuma I', color: '#b96b2c', text: '#1f1a14', aggr: 0.7, isNew: true,
    ability: 'Iron Kingdom of Hatti', abilityDesc: 'Start with Bronze Working. Mines give +1 Production.',
    mods: { startTech: 'bronze', mineProd: 1 }, uu: 'warchariot', ub: 'smeltery',
    cities: ['Hattusa', 'Kanesh', 'Carchemish', 'Nerik', 'Sapinuwa', 'Samuha', 'Kussara', 'Arinna', 'Zalpa', 'Tarsa', 'Ankuwa', 'Kummanni'] },
  tibet: { name: 'Tibet', adj: 'Tibetan', leader: 'Songtsen Gampo', color: '#ad3f7c', text: '#f7e7a9', aggr: 0.3, isNew: true,
    ability: 'Roof of the World', abilityDesc: 'Holy Sites get double adjacency from Mountains. Land units move through Hills at no extra cost.',
    mods: { holyMountain: 2, hillsFree: true }, uu: 'mountainguard', ub: 'dzong',
    cities: ['Lhasa', 'Shigatse', 'Gyantse', 'Tsetang', 'Chamdo', 'Nyingchi', 'Sakya', 'Gartok', 'Yarlung', 'Derge', 'Litang', 'Ngari'] },
  majapahit: { name: 'Majapahit', adj: 'Majapahit', leader: 'Hayam Wuruk', color: '#1c627d', text: '#f2c85b', aggr: 0.4, isNew: true,
    ability: 'Nusantara', abilityDesc: 'Coastal cities get +2 Gold and +1 Production. Harbors cost 50% less.',
    mods: { coastalGold: 2, coastalProd: 1, harborCheap: true }, uu: 'bhayangkara', ub: 'candi',
    cities: ['Trowulan', 'Kediri', 'Singhasari', 'Tuban', 'Gresik', 'Surabaya', 'Daha', 'Blambangan', 'Pajang', 'Demak', 'Sunda Kelapa', 'Bali'] },
  zimbabwe: { name: 'Great Zimbabwe', adj: 'Shona', leader: 'Mutota', color: '#8f9c2c', text: '#2a1c10', aggr: 0.4, isNew: true,
    ability: 'Stone Enclosures', abilityDesc: 'Commercial Hubs get +1 Gold per adjacent Pasture. Walls give +2 Culture and cost less.',
    mods: { commercialPasture: 1 }, uu: 'rozvi', ub: 'hillfort',
    cities: ['Great Zimbabwe', 'Khami', 'Danangombe', 'Naletale', 'Mapungubwe', 'Thulamela', 'Manyikeni', 'Zinjanja', 'Chipadze', 'Nyanga', 'Tsindi', 'Ruanga'] },
  cahokia: { name: 'Mississippians', adj: 'Mississippian', leader: 'Red Horn', color: '#7c5436', text: '#f2e3c4', aggr: 0.3, isNew: true,
    ability: 'Mound Builders', abilityDesc: 'Farms give +1 Food. +10% growth in every city.',
    mods: { farmFood: 1, growth: 0.1 }, uu: 'chunkey', ub: 'mound',
    cities: ['Cahokia', 'Etowah', 'Moundville', 'Spiro', 'Kincaid', 'Angel Mounds', 'Toqua', 'Ocmulgee', 'Parkin', 'Winterville', 'Emerald', 'Aztalan'] },
  swahili: { name: 'Swahili Coast', adj: 'Swahili', leader: 'al-Hasan ibn Sulaiman', color: '#e389b0', text: '#1d3a45', aggr: 0.2, isNew: true,
    ability: 'Monsoon Trade', abilityDesc: 'Each kind of luxury resource gives +3 Gold. Commercial Hubs give +2 Gold.',
    mods: { luxGold: 3, commercialGold: 2 }, uu: 'kilwabow', ub: 'stonetown',
    cities: ['Kilwa Kisiwani', 'Mombasa', 'Zanzibar', 'Lamu', 'Malindi', 'Gedi', 'Pate', 'Sofala', 'Mogadishu', 'Songo Mnara', 'Pemba', 'Barawa'] },
  timurids: { name: 'Timurids', adj: 'Timurid', leader: 'Timur', color: '#3aa1d9', text: '#1b2230', aggr: 0.9, isNew: true,
    ability: 'Conqueror of Samarkand', abilityDesc: 'Capturing a city grants Culture and Science. +25% Production toward siege units.',
    mods: { captureBonus: true, siegeProd: 0.25 }, uu: 'mubariz', ub: 'ulughbeg',
    cities: ['Samarkand', 'Herat', 'Bukhara', 'Shahrisabz', 'Tabriz', 'Mashhad', 'Balkh', 'Kabul', 'Merv', 'Urgench', 'Tashkent', 'Nishapur'] },
};

const BARB_COLOR = '#2a2522';

const DIFFICULTIES = {
  settler: { name: 'Settler', ai: 0.75, happy: 14 },
  prince:  { name: 'Prince', ai: 1.0, happy: 10 },
  king:    { name: 'King', ai: 1.2, happy: 9 },
  deity:   { name: 'Deity', ai: 1.5, happy: 8 },
};

const SPEEDS = {
  quick:    { name: 'Quick', mul: 0.67, turns: 360 },
  standard: { name: 'Standard', mul: 1.0, turns: 500 },
};

const MAP_SIZES = {
  small:    { name: 'Small', W: 44, H: 28 },
  standard: { name: 'Standard', W: 56, H: 36 },
  large:    { name: 'Large', W: 70, H: 44 },
};
