// Full-screen story cards over the scene.
//
//   ui.cards.chapter({ kicker, title, traveler, ms = 4500 }) -> Promise
//       black card: kicker letters fade in, the title with the amber rule, the traveler's portrait
//       and name; input is held until it ends
//   ui.cards.logo({ text = 'VOIDPATH', ms = 4000 }) -> Promise      the logotype over the scene
//   ui.cards.caption(text, { ms = 2500 }) -> Promise                 centred caption, never blocks input
//   ui.cards.credits({ lines, transparent, onSkip, speed }) -> Promise
//       lines: { head } | { role, name } | { cast: charId, name, role } | { text } | { gap: n };
//       scrolls at a readable pace (speed px/s, default 46), then "Everything you saw and heard was
//       generated by code"; holding Confirm (or a finger) for 1 s skips (onSkip is called).
//       transparent: true scrolls over the live field with a dark band behind the text.
//   ui.cards.end({ text = 'THE END' }) -> Promise                    waits for Confirm or a tap
//   ui.cards.clear()     drop every card and caption at once (aborted scripts); their promises resolve
//
// `ms` scales a card's whole timeline (the cutscene runner passes about 300 in skip mode); `hold:
// true` keeps a chapter card or logo up until clear() (previews, screenshots).
// isBlocking is true while a chapter card, logo, credits or THE END is up.

import { el, injectCSS } from '../core/util.js';
import { glyph, onTap, richText } from './theme.js';

const CSS = `
.vp-cards { z-index: 57; }
.vp-sc { position: absolute; inset: 0; display: flex; flex-direction: column; align-items: center; justify-content: center; text-align: center;
  padding: 24px 16px calc(24px + var(--vp-safe-bottom)); box-sizing: border-box; overflow: hidden; --k: 1;
  opacity: 0; transition: opacity calc(var(--k) * .5s) ease; }
.vp-sc.is-on { opacity: 1; }
.vp-sc.is-out { opacity: 0; transition-duration: calc(var(--k) * .7s); }
.vp-sc-black { background: #000; }

/* chapter */
.vp-chap::before { content: ''; position: absolute; inset: 0; pointer-events: none;
  background: radial-gradient(60% 50% at 50% 48%, color-mix(in srgb, var(--acc) 10%, transparent), transparent 70%),
              repeating-linear-gradient(0deg, rgba(255,255,255,.018) 0 1px, transparent 1px 4px); }
.vp-chap-kick { display: flex; justify-content: center; gap: .02em; padding-left: .55em; font: 600 clamp(13px, 1.5vw, 18px)/1 var(--vp-font-display); letter-spacing: .55em;
  text-transform: uppercase; color: #cfe6ff; text-shadow: 0 0 12px rgba(127,227,255,.45); }
.vp-chap-kick span { opacity: 0; animation: vp-chap-letter calc(var(--k) * .5s) ease-out both; animation-delay: calc(var(--k) * (.45s + var(--i) * .055s)); white-space: pre; }
@keyframes vp-chap-letter { from { opacity: 0; filter: blur(3px); } to { opacity: 1; filter: none; } }
.vp-chap-title { position: relative; margin: clamp(14px, 2.4vh, 26px) 0 0; padding-left: .26em; font: 800 clamp(40px, 8.4vw, 104px)/1 var(--vp-font-display); letter-spacing: .26em;
  white-space: nowrap; color: transparent; -webkit-background-clip: text; background-clip: text;
  background-image: linear-gradient(180deg, #ffffff 0%, #e8f6ff 42%, #a8dcff 50%, #5684bb 52%, #a8d2f5 72%, #f6fbff 100%);
  filter: drop-shadow(0 0 18px rgba(127,227,255,.28)); animation: vp-chap-title calc(var(--k) * 1.3s) var(--vp-ease-out) both; animation-delay: calc(var(--k) * 1.15s); }
@keyframes vp-chap-title { from { opacity: 0; letter-spacing: .5em; } to { opacity: 1; } }
.vp-chap .vp-rule { animation: vp-chap-rule calc(var(--k) * 1s) var(--vp-ease-out) both; animation-delay: calc(var(--k) * 1.7s); }
@keyframes vp-chap-rule { from { opacity: 0; transform: scaleX(.15); } }
.vp-chap-trav { display: flex; align-items: center; gap: 18px; margin-top: clamp(18px, 3.4vh, 36px); animation: vp-chap-up calc(var(--k) * .9s) var(--vp-ease-out) both; animation-delay: calc(var(--k) * 2.1s); }
.vp-chap-trav .vp-portrait { width: 96px; height: 96px; --ps: 96px; box-shadow: 0 0 0 1px rgba(5,7,13,.6), 0 0 26px color-mix(in srgb, var(--acc) 40%, transparent); }
.vp-chap-trav div { text-align: left; display: grid; gap: 8px; }
.vp-chap-trav b { font: 700 22px/1 var(--vp-font-display); letter-spacing: .24em; color: #fff; text-shadow: 0 0 14px color-mix(in srgb, var(--acc) 55%, transparent); }
.vp-chap-trav small { font: 600 12px/1 var(--vp-font-ui); letter-spacing: .32em; text-transform: uppercase; color: var(--acc); }
@keyframes vp-chap-up { from { opacity: 0; transform: translateY(10px); } }

/* logo */
.vp-sc-logo { background: radial-gradient(70% 55% at 50% 45%, rgba(5,7,13,.55), rgba(5,7,13,0) 75%); }
.vp-sc-logo .vp-logo { animation: vp-sc-logo calc(var(--k) * 1.6s) var(--vp-ease-out) both; }
.vp-sc-logo .vp-rule { animation: vp-chap-rule calc(var(--k) * 1.1s) var(--vp-ease-out) both; animation-delay: calc(var(--k) * .7s); }
@keyframes vp-sc-logo { from { opacity: 0; transform: scale(1.05); } }

/* caption */
.vp-cap-card { position: absolute; left: 0; right: 0; top: 40%; display: flex; justify-content: center; align-items: center; gap: 18px; pointer-events: none;
  opacity: 0; transition: opacity .45s ease; }
.vp-cap-card.is-on { opacity: 1; }
.vp-cap-card::before { content: ''; position: absolute; left: 50%; top: 50%; width: min(820px, 110%); height: 260%; transform: translate(-50%, -50%); z-index: -1;
  background: radial-gradient(50% 50% at 50% 50%, rgba(5,7,13,.6), rgba(5,7,13,0)); }
.vp-cap-card i { width: clamp(24px, 8vw, 110px); height: 1px; background: linear-gradient(90deg, rgba(190,236,255,0), rgba(190,236,255,.8)); }
.vp-cap-card i:last-child { transform: scaleX(-1); }
.vp-cap-card span { padding-left: .34em; max-width: 80vw; font: 600 clamp(15px, 1.7vw, 20px)/1.4 var(--vp-font-display); letter-spacing: .34em; text-transform: uppercase; color: #eaf6ff;
  text-shadow: 0 0 12px rgba(127,227,255,.4), 0 1px 0 rgba(0,0,0,.6); }

/* credits */
.vp-cred { justify-content: flex-start; padding: 0; }
.vp-cred.is-clear { background: linear-gradient(90deg, rgba(3,4,8,0), rgba(3,4,8,.62) 28%, rgba(3,4,8,.62) 72%, rgba(3,4,8,0)),
  linear-gradient(180deg, rgba(3,4,8,.5), rgba(3,4,8,0) 22%, rgba(3,4,8,0) 78%, rgba(3,4,8,.5)); }
.vp-cred-roll { position: absolute; left: 0; right: 0; top: 0; display: flex; flex-direction: column; align-items: center; will-change: transform; }
.vp-cred-head { margin: 34px 0 22px; padding-left: .3em; font: 800 clamp(30px, 4.6vw, 54px)/1 var(--vp-font-display); letter-spacing: .3em; color: transparent;
  -webkit-background-clip: text; background-clip: text; background-image: linear-gradient(180deg, #fff 0%, #e8f6ff 42%, #a8dcff 50%, #5684bb 52%, #a8d2f5 72%, #f6fbff 100%); }
.vp-cred-role { display: grid; grid-template-columns: minmax(0, 1fr) minmax(0, 1fr); gap: 26px; width: min(760px, 92vw); margin: 7px 0; align-items: baseline; }
.vp-cred-role span { text-align: right; font: 600 13px/1.4 var(--vp-font-ui); letter-spacing: .26em; text-transform: uppercase; color: var(--vp-ink-dim); }
.vp-cred-role b { text-align: left; font: 600 19px/1.4 var(--vp-font-display); letter-spacing: .1em; color: #f4f9ff; }
.vp-cred-cast { display: grid; grid-template-columns: 72px minmax(0, 1fr); gap: 18px; align-items: center; width: min(460px, 86vw); margin: 10px 0; text-align: left; }
.vp-cred-cast .vp-portrait { width: 72px; height: 72px; --ps: 72px; }
.vp-cred-cast b { display: block; font: 700 20px/1.2 var(--vp-font-display); letter-spacing: .18em; color: #fff; text-shadow: 0 0 12px color-mix(in srgb, var(--acc) 50%, transparent); }
.vp-cred-cast small { display: block; margin-top: 6px; font: 600 12px/1.3 var(--vp-font-ui); letter-spacing: .28em; text-transform: uppercase; color: var(--acc); }
.vp-cred-text { width: min(620px, 88vw); margin: 10px 0; font: 400 italic 17px/1.6 var(--vp-font-ui); color: #cfe0f5; }
.vp-cred-end { position: absolute; inset: 0; display: grid; place-items: center; padding: 0 24px; opacity: 0; transition: opacity 1.2s ease; pointer-events: none; }
.vp-cred-end.is-on { opacity: 1; }
.vp-cred-end p { max-width: 640px; margin: 0; font: 500 clamp(16px, 1.8vw, 21px)/1.6 var(--vp-font-ui); letter-spacing: .08em; color: #e9f2ff; text-shadow: 0 0 14px rgba(127,227,255,.3); }
.vp-hold { position: absolute; right: calc(22px + var(--vp-safe-right)); bottom: calc(20px + var(--vp-safe-bottom)); display: flex; align-items: center; gap: 10px;
  font: 600 12px/1 var(--vp-font-ui); letter-spacing: .22em; text-transform: uppercase; color: var(--vp-ink-faint); }
.vp-hold-bar { width: 60px; height: 3px; background: rgba(140,214,255,.16); }
.vp-hold-bar i { display: block; height: 100%; background: var(--vp-amber); transform-origin: 0 50%; transform: scaleX(var(--p, 0)); }

/* the end */
.vp-end-t { padding-left: .5em; font: 700 clamp(30px, 5.2vw, 64px)/1 var(--vp-font-display); letter-spacing: .5em; color: #f4f9ff;
  text-shadow: 0 0 22px rgba(127,227,255,.35); animation: vp-end-t calc(var(--k) * 2.2s) ease both; animation-delay: calc(var(--k) * .3s); }
@keyframes vp-end-t { from { opacity: 0; letter-spacing: .8em; } }
.vp-sc-end .vp-rule { width: min(420px, 70vw); animation: vp-chap-rule calc(var(--k) * 1.2s) var(--vp-ease-out) both; animation-delay: calc(var(--k) * 1.2s); }
.vp-end-p { margin-top: 44px; display: flex; align-items: center; gap: 12px; font: 600 13px/1 var(--vp-font-ui); letter-spacing: .3em; text-transform: uppercase; color: var(--vp-ink-dim);
  opacity: 0; transition: opacity .6s; }
.vp-end-p.is-on { opacity: 1; animation: vp-blink 1.9s ease-in-out infinite; }

@media (max-width: 640px) {
  .vp-chap-kick { letter-spacing: .34em; padding-left: .34em; }
  .vp-chap-title { letter-spacing: .14em; padding-left: .14em; font-size: clamp(32px, 11vw, 48px); }
  .vp-chap-trav .vp-portrait { width: 72px; height: 72px; --ps: 72px; }
  .vp-chap-trav b { font-size: 18px; }
  .vp-cred-role { grid-template-columns: 1fr; gap: 4px; text-align: center; margin: 10px 0; }
  .vp-cred-role span, .vp-cred-role b { text-align: center; }
  .vp-end-t { letter-spacing: .3em; padding-left: .3em; }
}
`;

const CLOSING = 'Everything you saw and heard was generated by code.';

export class Cards {
  constructor(ui) {
    this.ui = ui;
    injectCSS('vp-cards', CSS);
    this.isBlocking = false;
    this._cur = null;           // { view, kind, resolve, ... }
    this._captions = new Set(); // { node, resolve, timers }
    this.root = el('div', { class: 'vp-layer vp-cards' });
    ui.root.appendChild(this.root);
  }

  get isOpen() { return !!this._cur; }

  // ------------------------------------------------------------------ cards

  chapter({ kicker = '', title = '', traveler = null, ms = 4500, hold = false } = {}) {
    const k = ms / 4500;
    const letters = el('div', { class: 'vp-chap-kick', 'aria-label': kicker }, [...String(kicker)].map((ch, i) => {
      const s = el('span', { text: ch });
      s.style.setProperty('--i', i);
      return s;
    }));
    const accent = traveler ? this.ui._accentOf(traveler) : '#7fe3ff';
    const trav = traveler ? el('div', { class: 'vp-chap-trav' }, [
      this.ui.portraitEl(traveler, { size: 96, accent }),
      el('div', {}, [el('b', { text: this.ui.memberName(traveler) }), el('small', { text: this.ui.memberClass(traveler) || 'Traveler' })]),
    ]) : null;
    const view = el('div', { class: 'vp-sc vp-sc-black vp-chap', role: 'dialog', 'aria-label': `${kicker} ${title}` }, [
      letters, el('h1', { class: 'vp-chap-title', text: title }), rule(), trav,
    ]);
    view.style.setProperty('--acc', accent);
    setTimeout(() => this.ui.sfx('card'), 1150 * k);
    return this._open(view, 'chapter', { k, ms, fadeOut: 700 * k, wait: hold });
  }

  logo({ text = 'VOIDPATH', ms = 4000, hold = false } = {}) {
    const k = ms / 4000;
    const ghost = (cls) => el('span', { class: `vp-logo-ghost ${cls}`, 'aria-hidden': 'true', text });
    const view = el('div', { class: 'vp-sc vp-sc-logo', role: 'img', 'aria-label': text }, [
      el('h1', { class: 'vp-logo' }, [ghost('c'), ghost('m'), el('span', { class: 'vp-logo-main', text })]), rule(),
    ]);
    return this._open(view, 'logo', { k, ms, fadeOut: 800 * k, wait: hold });
  }

  /** Centred caption over the scene ("En route"); never blocks input. */
  caption(text, { ms = 2500 } = {}) {
    const node = el('div', { class: 'vp-cap-card', role: 'status' }, [el('i'), el('span', {}, [richText(text)]), el('i')]);
    this.root.appendChild(node);
    void node.offsetWidth;
    node.classList.add('is-on');
    const fade = Math.min(450, ms * 0.3);
    node.style.transitionDuration = `${fade}ms`;
    return new Promise((resolve) => {
      const cap = { node, resolve, timers: [] };
      const done = () => { clearTimeout(cap.timers[0]); clearTimeout(cap.timers[1]); node.remove(); this._captions.delete(cap); resolve(); };
      cap.done = done;
      cap.timers = [setTimeout(() => node.classList.remove('is-on'), Math.max(0, ms - fade)), setTimeout(done, ms)];
      this._captions.add(cap);
    });
  }

  clear() {
    this._finish(true);
    for (const cap of [...this._captions]) cap.done();
  }

  credits({ lines = [], transparent = false, onSkip = null, speed = 46 } = {}) {
    const roll = el('div', { class: 'vp-cred-roll' }, lines.map((l) => this._creditLine(l)));
    const end = el('div', { class: 'vp-cred-end' }, [el('p', { text: CLOSING })]);
    this._holdBar = el('i');
    this._holdHint = el('div', { class: 'vp-hold' }, [el('span', { class: 'vp-hold-g' }), 'Hold to skip', el('span', { class: 'vp-hold-bar' }, [this._holdBar])]);
    const view = el('div', { class: `vp-sc vp-cred ${transparent ? 'is-clear' : 'vp-sc-black'}`, role: 'dialog', 'aria-label': 'Credits' }, [roll, end, this._holdHint]);
    // holding a finger anywhere skips too (pointer hold tracked here, Confirm in update)
    view.addEventListener('pointerdown', () => { this._pointerHeld = true; });
    for (const t of ['pointerup', 'pointercancel', 'pointerleave']) view.addEventListener(t, () => { this._pointerHeld = false; });
    const p = this._open(view, 'credits', { k: 1, fadeOut: 900, onSkip });
    Object.assign(this._cur, { roll, end, speed, y: 0, phase: 'roll', held: 0, endT: 0 });
    this._pointerHeld = false;
    this._refreshHoldGlyph();
    return p;
  }

  end({ text = 'THE END', ms = 1600 } = {}) {
    const k = ms / 1600;
    const prompt = el('div', { class: 'vp-end-p' }, [el('span', { class: 'vp-end-g' }), 'Continue']);
    const view = el('div', { class: 'vp-sc vp-sc-black vp-sc-end', role: 'dialog', 'aria-label': text }, [
      el('div', { class: 'vp-end-t', text }), rule(), prompt,
    ]);
    onTap(view, () => { if (this._cur && this._cur.view === view && this._cur.ready) this._finish(); });
    const p = this._open(view, 'end', { k, fadeOut: 600 * k, wait: true });
    prompt.firstChild.replaceChildren(glyph('confirm', this.ui.input.lastDevice));
    setTimeout(() => {
      if (!this._cur || this._cur.view !== view) return;
      this._cur.ready = true;
      prompt.classList.add('is-on');
    }, ms);
    return p;
  }

  // ------------------------------------------------------------------ frame

  update(dt, focused) {
    const c = this._cur;
    if (!c) return;
    if (c.kind === 'credits') this._updateCredits(c, dt, focused);
    if (!focused) return;
    const inp = this.ui.input;
    if (c.kind === 'end' && c.ready && inp.pressed('confirm')) { inp.consume('confirm'); this._finish(); return; }
    for (const a of ['confirm', 'cancel', 'menu']) inp.consume(a);      // cards hold input
  }

  _updateCredits(c, dt, focused) {
    const held = this._pointerHeld || (focused && this.ui.input.down('confirm'));
    c.held = held ? c.held + dt : 0;
    this._holdHint.style.opacity = c.held > 0.05 ? '1' : '';
    this._holdBar.style.setProperty('--p', Math.min(1, c.held).toFixed(3));
    if (c.held >= 1) {
      if (c.onSkip) c.onSkip();
      this._finish();
      return;
    }
    if (c.phase === 'roll') {
      c.y += c.speed * dt;
      const h = this.root.clientHeight;
      c.roll.style.transform = `translateY(${(h - c.y).toFixed(1)}px)`;
      if (c.y > h + c.roll.offsetHeight + 20) { c.phase = 'closing'; c.end.classList.add('is-on'); }
    } else if ((c.endT += dt) > 5.2) {
      c.phase = 'done';
      this._finish();
    } else if (c.endT > 4) c.end.classList.remove('is-on');
  }

  // ------------------------------------------------------------------ plumbing

  _creditLine(l) {
    if (l.gap) return el('div', { style: { height: `${24 * l.gap}px`, flex: 'none' } });
    if (l.head) return el('div', { class: 'vp-cred-head', text: l.head });
    if (l.cast) {
      const accent = this.ui._accentOf(l.cast) || '#7fe3ff';
      const row = el('div', { class: 'vp-cred-cast' }, [
        this.ui.portraitEl(l.cast, { size: 72, accent }),
        el('div', {}, [el('b', { text: l.name || this.ui.memberName(l.cast) }), l.role ? el('small', { text: l.role }) : null]),
      ]);
      row.style.setProperty('--acc', accent);
      return row;
    }
    if (l.role || l.name) return el('div', { class: 'vp-cred-role' }, [el('span', { text: l.role || '' }), el('b', { text: l.name || '' })]);
    return el('div', { class: 'vp-cred-text' }, [richText(l.text || '')]);
  }

  _refreshHoldGlyph() {
    const dev = this.ui.input.lastDevice;
    this._holdHint.firstChild.replaceChildren(dev === 'touch' ? '' : glyph('confirm', dev));
  }

  /** Show a blocking card; it ends after `ms` (or when `wait` cards are confirmed). */
  _open(view, kind, { k = 1, ms = 0, fadeOut = 600, wait = false, onSkip = null } = {}) {
    if (this._cur) this._finish(true);
    view.style.setProperty('--k', k);
    this.root.appendChild(view);
    this.isBlocking = true;
    this.ui._ctxPush('cards', 'card');
    void view.offsetWidth;
    view.classList.add('is-on');
    return new Promise((resolve) => {
      this._cur = { view, kind, resolve, fadeOut, onSkip, ready: false, timer: 0 };
      if (ms && !wait) this._cur.timer = setTimeout(() => this._finish(), Math.max(0, ms - fadeOut));
    });
  }

  _finish(instant = false) {
    const c = this._cur;
    if (!c) return;
    this._cur = null;
    clearTimeout(c.timer);
    this.isBlocking = false;
    this.ui._ctxPop('cards');
    c.view.classList.add('is-out');
    const done = () => { c.view.remove(); c.resolve(); };
    if (instant) done();
    else setTimeout(done, c.fadeOut);
  }
}

/** The amber rule with a diamond (title-screen style). */
function rule() {
  return el('div', { class: 'vp-rule' }, [el('i'), el('b'), el('i')]);
}
